export const PAISES: { nombre: string, valor: string }[] = [
  { nombre: 'Afganistán', valor: 'afganistan' },
  { nombre: 'Albania', valor: 'albania' },
  { nombre: 'Alemania', valor: 'alemania' },
  { nombre: 'Andorra', valor: 'andorra' },
  { nombre: 'Angola', valor: 'angola' },
  { nombre: 'Antigua y Barbuda', valor: 'antigua_y_barbuda' },
  { nombre: 'Arabia Saudita', valor: 'arabia_saudita' },
  { nombre: 'Argelia', valor: 'argelia' },
  { nombre: 'Argentina', valor: 'argentina' },
  { nombre: 'Armenia', valor: 'armenia' },
  { nombre: 'Australia', valor: 'australia' },
  { nombre: 'Austria', valor: 'austria' },
  { nombre: 'Azerbaiyán', valor: 'azerbaiyan' },
  { nombre: 'Bahamas', valor: 'bahamas' },
  { nombre: 'Bangladés', valor: 'banglades' },
  { nombre: 'Barbados', valor: 'barbados' },
  { nombre: 'Baréin', valor: 'barein' },
  { nombre: 'Bélgica', valor: 'belgica' },
  { nombre: 'Belice', valor: 'belice' },
  { nombre: 'Benín', valor: 'benin' },
  { nombre: 'Bielorrusia', valor: 'bielorrusia' },
  { nombre: 'Birmania', valor: 'birmania' },
  { nombre: 'Bolivia', valor: 'bolivia' },
  { nombre: 'Bosnia y Herzegovina', valor: 'bosnia_y_herzegovina' },
  { nombre: 'Botsuana', valor: 'botsuana' },
  { nombre: 'Brasil', valor: 'brasil' },
  { nombre: 'Brunéi', valor: 'brunei' },
  { nombre: 'Bulgaria', valor: 'bulgaria' },
  { nombre: 'Burkina Faso', valor: 'burkina_faso' },
  { nombre: 'Burundi', valor: 'burundi' },
  { nombre: 'Bután', valor: 'butan' },
  { nombre: 'Cabo Verde', valor: 'cabo_verde' },
  { nombre: 'Camboya', valor: 'camboya' },
  { nombre: 'Camerún', valor: 'camerun' },
  { nombre: 'Canadá', valor: 'canada' },
  { nombre: 'Catar', valor: 'catar' },
  { nombre: 'Chad', valor: 'chad' },
  { nombre: 'Chile', valor: 'chile' },
  { nombre: 'China', valor: 'china' },
  { nombre: 'Chipre', valor: 'chipre' },
  { nombre: 'Colombia', valor: 'colombia' },
  { nombre: 'Comoras', valor: 'comoras' },
  { nombre: 'Corea del Norte', valor: 'corea_del_norte' },
  { nombre: 'Corea del Sur', valor: 'corea_del_sur' },
  { nombre: 'Costa de Marfil', valor: 'costa_de_marfil' },
  { nombre: 'Costa Rica', valor: 'costa_rica' },
  { nombre: 'Croacia', valor: 'croacia' },
  { nombre: 'Cuba', valor: 'cuba' },
  { nombre: 'Dinamarca', valor: 'dinamarca' },
  { nombre: 'Dominica', valor: 'dominica' },
  { nombre: 'Ecuador', valor: 'ecuador' },
  { nombre: 'Egipto', valor: 'egipto' },
  { nombre: 'El Salvador', valor: 'el_salvador' },
  { nombre: 'Emiratos Árabes Unidos', valor: 'emiratos_arabes_unidos' },
  { nombre: 'Eritrea', valor: 'eritrea' },
  { nombre: 'Eslovaquia', valor: 'eslovaquia' },
  { nombre: 'Eslovenia', valor: 'eslovenia' },
  { nombre: 'España', valor: 'espana' },
  { nombre: 'Estados Unidos', valor: 'estados_unidos' },
  { nombre: 'Estonia', valor: 'estonia' },
  { nombre: 'Etiopía', valor: 'etiopia' },
  { nombre: 'Filipinas', valor: 'filipinas' },
  { nombre: 'Finlandia', valor: 'finlandia' },
  { nombre: 'Fiyi', valor: 'fiyi' },
  { nombre: 'Francia', valor: 'francia' },
  { nombre: 'Gabón', valor: 'gabon' },
  { nombre: 'Gambia', valor: 'gambia' },
  { nombre: 'Georgia', valor: 'georgia' },
  { nombre: 'Ghana', valor: 'ghana' },
  { nombre: 'Granada', valor: 'granada' },
  { nombre: 'Grecia', valor: 'grecia' },
  { nombre: 'Guatemala', valor: 'guatemala' },
  { nombre: 'Guyana', valor: 'guyana' },
  { nombre: 'Guinea', valor: 'guinea' },
  { nombre: 'Guinea-Bisáu', valor: 'guinea_bisau' },
  { nombre: 'Guinea Ecuatorial', valor: 'guinea_ecuatorial' },
  { nombre: 'Haití', valor: 'haiti' },
  { nombre: 'Honduras', valor: 'honduras' },
  { nombre: 'Hungría', valor: 'hungria' },
  { nombre: 'India', valor: 'india' },
  { nombre: 'Indonesia', valor: 'indonesia' },
  { nombre: 'Irak', valor: 'irak' },
  { nombre: 'Irán', valor: 'iran' },
  { nombre: 'Irlanda', valor: 'irlanda' },
  { nombre: 'Islandia', valor: 'islandia' },
  { nombre: 'Islas Marshall', valor: 'islas_marshall' },
  { nombre: 'Islas Salomón', valor: 'islas_salomon' },
  { nombre: 'Israel', valor: 'israel' },
  { nombre: 'Italia', valor: 'italia' },
  { nombre: 'Jamaica', valor: 'jamaica' },
  { nombre: 'Japón', valor: 'japon' },
  { nombre: 'Jordania', valor: 'jordania' },
  { nombre: 'Kazajistán', valor: 'kazajistan' },
  { nombre: 'Kenia', valor: 'kenia' },
  { nombre: 'Kirguistán', valor: 'kirguistan' },
  { nombre: 'Kiribati', valor: 'kiribati' },
  { nombre: 'Kuwait', valor: 'kuwait' },
  { nombre: 'Laos', valor: 'laos' },
  { nombre: 'Lesoto', valor: 'lesoto' },
  { nombre: 'Letonia', valor: 'letonia' },
  { nombre: 'Líbano', valor: 'libano' },
  { nombre: 'Liberia', valor: 'liberia' },
  { nombre: 'Libia', valor: 'libia' },
  { nombre: 'Liechtenstein', valor: 'liechtenstein' },
  { nombre: 'Lituania', valor: 'lituania' },
  { nombre: 'Luxemburgo', valor: 'luxemburgo' },
  { nombre: 'Madagascar', valor: 'madagascar' },
  { nombre: 'Malasia', valor: 'malasia' },
  { nombre: 'Malaui', valor: 'malaui' },
  { nombre: 'Maldivas', valor: 'maldivas' },
  { nombre: 'Malí', valor: 'mali' },
  { nombre: 'Malta', valor: 'malta' },
  { nombre: 'Marruecos', valor: 'marruecos' },
  { nombre: 'Mauricio', valor: 'mauricio' },
  { nombre: 'Mauritania', valor: 'mauritania' },
  { nombre: 'México', valor: 'mexico' },
  { nombre: 'Micronesia', valor: 'micronesia' },
  { nombre: 'Moldavia', valor: 'moldavia' },
  { nombre: 'Mónaco', valor: 'monaco' },
  { nombre: 'Mongolia', valor: 'mongolia' },
  { nombre: 'Montenegro', valor: 'montenegro' },
  { nombre: 'Mozambique', valor: 'mozambique' },
  { nombre: 'Namibia', valor: 'namibia' },
  { nombre: 'Nauru', valor: 'nauru' },
  { nombre: 'Nepal', valor: 'nepal' },
  { nombre: 'Nicaragua', valor: 'nicaragua' },
  { nombre: 'Níger', valor: 'niger' },
  { nombre: 'Nigeria', valor: 'nigeria' },
  { nombre: 'Noruega', valor: 'noruega' },
  { nombre: 'Nueva Zelanda', valor: 'nueva_zelanda' },
  { nombre: 'Omán', valor: 'oman' },
  { nombre: 'Países Bajos', valor: 'paises_bajos' },
  { nombre: 'Pakistán', valor: 'pakistan' },
  { nombre: 'Palaos', valor: 'palaos' },
  { nombre: 'Panamá', valor: 'panama' },
  { nombre: 'Papúa Nueva Guinea', valor: 'papua_nueva_guinea' },
  { nombre: 'Paraguay', valor: 'paraguay' },
  { nombre: 'Perú', valor: 'peru' },
  { nombre: 'Polonia', valor: 'polonia' },
  { nombre: 'Portugal', valor: 'portugal' },
  { nombre: 'Reino Unido', valor: 'reino_unido' },
  { nombre: 'República Centroafricana', valor: 'republica_centroafricana' },
  { nombre: 'República Checa', valor: 'republica_checa' },
  { nombre: 'República del Congo', valor: 'republica_del_congo' },
  { nombre: 'República Democrática del Congo', valor: 'republica_democratica_del_congo' },
  { nombre: 'República Dominicana', valor: 'republica_dominicana' },
  { nombre: 'Ruanda', valor: 'ruanda' },
  { nombre: 'Rumanía', valor: 'rumania' },
  { nombre: 'Rusia', valor: 'rusia' },
  { nombre: 'Samoa', valor: 'samoa' },
  { nombre: 'San Cristóbal y Nieves', valor: 'san_cristobal_y_nieves' },
  { nombre: 'San Marino', valor: 'san_marino' },
  { nombre: 'San Vicente y las Granadinas', valor: 'san_vicente_y_las_granadinas' },
  { nombre: 'Santa Lucía', valor: 'santa_lucia' },
  { nombre: 'Santo Tomé y Príncipe', valor: 'santo_tome_y_principe' },
  { nombre: 'Senegal', valor: 'senegal' },
  { nombre: 'Serbia', valor: 'serbia' },
  { nombre: 'Seychelles', valor: 'seychelles' },
  { nombre: 'Sierra Leona', valor: 'sierra_leona' },
  { nombre: 'Singapur', valor: 'singapur' },
  { nombre: 'Siria', valor: 'siria' },
  { nombre: 'Somalia', valor: 'somalia' },
  { nombre: 'Sri Lanka', valor: 'sri_lanka' },
  { nombre: 'Suazilandia', valor: 'suazilandia' },
  { nombre: 'Sudáfrica', valor: 'sudafrica' },
  { nombre: 'Sudán', valor: 'sudan' },
  { nombre: 'Sudán del Sur', valor: 'sudan_del_sur' },
  { nombre: 'Suecia', valor: 'suecia' },
  { nombre: 'Suiza', valor: 'suiza' },
  { nombre: 'Surinam', valor: 'surinam' },
  { nombre: 'Tailandia', valor: 'tailandia' },
  { nombre: 'Tanzania', valor: 'tanzania' },
  { nombre: 'Tayikistán', valor: 'tayikistan' },
  { nombre: 'Timor Oriental', valor: 'timor_oriental' },
  { nombre: 'Togo', valor: 'togo' },
  { nombre: 'Tonga', valor: 'tonga' },
  { nombre: 'Trinidad y Tobago', valor: 'trinidad_y_tobago' },
  { nombre: 'Túnez', valor: 'tunez' },
  { nombre: 'Turkmenistán', valor: 'turkmenistan' },
  { nombre: 'Turquía', valor: 'turquia' },
  { nombre: 'Tuvalu', valor: 'tuvalu' },
  { nombre: 'Ucrania', valor: 'ucrania' },
  { nombre: 'Uganda', valor: 'uganda' },
  { nombre: 'Uruguay', valor: 'uruguay' },
  { nombre: 'Uzbekistán', valor: 'uzbekistan' },
  { nombre: 'Vanuatu', valor: 'vanuatu' },
  { nombre: 'Vaticano', valor: 'vaticano' },
  { nombre: 'Venezuela', valor: 'venezuela' },
  { nombre: 'Vietnam', valor: 'vietnam' },
  { nombre: 'Yemen', valor: 'yemen' },
  { nombre: 'Yibuti', valor: 'yibuti' },
  { nombre: 'Zambia', valor: 'zambia' },
  { nombre: 'Zimbabue', valor: 'zimbabue' },
  { nombre: 'Otro', valor: 'otro' }
];